### ISSUE TITLE
Can't it  get the eventlist??How to reslove this problem?

### ISSUE THREAD

**Issue by huang122124** [alex-krestin/bet365parser#4]
Trying to get events list from OVInPlay_1_3 channel.
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
        at java.util.ArrayList.rangeCheck(Unknown Source)
        at java.util.ArrayList.get(Unknown Source)
        at it.rehelpstudio.bet365.parser.Bet365Parser.powRequest(Bet365Parser.java:318)

**Comment by huang122124** [comment]
Plaease answer me,thanks.
